### ISSUE TITLE
Artifacts from batch iterator

### ISSUE THREAD

**Issue by zoroppz** [DIAGNijmegen/pathology-whole-slide-data#18]
When using batch iterator for extracting patches at 8 um/px there are some artifacts in the extracted patches. Few examples of this:

![image](https://user-images.githubusercontent.com/49131154/163732481-27963ea5-885f-47d6-9b11-76d8dc34e243.png)

![image](https://user-images.githubusercontent.com/49131154/163732496-140720d1-fde9-4a1f-9d6c-48eaaa82fc45.png)

The user config used:

```
wholeslidedata:
    default:
        seed: 123
        yaml_source: tigerdatasubset.yml
        
        label_map:
            roi: 0
            invasive tumor: 1
            tumor-associated stroma: 2
            in-situ tumor: 3 
            healthy glands: 4
            necrosis not in-situ: 5
            inflamed stroma: 6
            rest: 7
            
        annotation_parser:
            sample_label_names: ['roi']
            
        batch_shape:
            batch_size: 2
            spacing: 8
            shape: [256, 256, 3]

        point_sampler:
            attribute: RandomPointSampler
            buffer: -128
            
```

the data subset used :
```
--- 
training: 
  - 
    wsa: 
      path: /data/wsirois/wsi-level-annotations/annotations-tissue-cells-xmls/100B.xml
    wsi: 
      path: /data/wsirois/wsi-level-annotations/images/100B.tif
```

To reproduce this the "Tiger-BatchIterator Introduction" notebook can be run with the above settings. Is this a known issue?
