### ISSUE TITLE
weighted sampling of patches based on different labels for segmentation

### ISSUE THREAD

**Issue by Vishwesh4** [DIAGNijmegen/pathology-whole-slide-data#6]
Hi,
Can you please point out, how to perform weighted sampling of patches based on different labels for segmentation. I have been trying to fiddle with the config files but can't yet figure out. 
Thanks

**Comment by martvanrijthoven** [comment]
Dear Vishwesh4,

Thanks for your issue. I can imagine that the config is a bit confusing. My apologies for the lack of documentation. I hope I will find time to write more documentation soon.

I checked the [WeightedLabelSampler](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/5020ea703cb9962776eaef8d8a92d32b85916e4b/wholeslidedata/samplers/labelsampler.py#L113) and I have improved the interface. Now you can give a dictionary with label names and weights as values. The following config will show how you can use the  [WeightedLabelSampler](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/5020ea703cb9962776eaef8d8a92d32b85916e4b/wholeslidedata/samplers/labelsampler.py#L113) for example in this [notebook](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/main/notebooks/04%20-%20BatchIterator.ipynb)

```yaml
wholeslidedata:
    default:
        yaml_source: data.yml
        seed: 2

        label_map:
            stroma: 1
            tumor: 2
            lymphocytes: 3

        annotation_sources: 
            filters: ['xml']
            
        batch_shape:
            batch_size: 8
            spacing: 0.5
            shape: [256, 256, 3]
            
        label_sampler@replace=true:
            module: wholeslidedata.samplers.labelsampler
            attribute: WeightedLabelSampler
            labels: 
                stroma: 0.5
                tumor: 0.25
                lymphocytes: 0.25
            seed: ${wholeslidedata:seed}

        annotation_sampler:
            attribute: OrderedAnnotationSampler
            
        point_sampler:
            attribute: RandomPointSampler
            
```


Let me explain a bit what happens here. Normally you can override values in the config and you only need to override values that you want to change. But the  [WeightedLabelSampler](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/5020ea703cb9962776eaef8d8a92d32b85916e4b/wholeslidedata/samplers/labelsampler.py#L113) accepts a dictionary 'labels', with label names as keys and weights as values. Therefore we can not override the values of the label sampler because the argument 'labels' is of a different type than e.g., in the [BalancedLabelSampler](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/5020ea703cb9962776eaef8d8a92d32b85916e4b/wholeslidedata/samplers/labelsampler.py#L85) in which the argument labels is expected to be a list. However, we can replace the full label sampler config by adding '@replace=true". This means that we have to define the full config for the label sampler, the module, attribute, and all the arguments for the [WeightedLabelSampler](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/5020ea703cb9962776eaef8d8a92d32b85916e4b/wholeslidedata/samplers/labelsampler.py#L113) class. The arguments of the [WeightedLabelSampler](https://github.com/DIAGNijmegen/pathology-whole-slide-data/blob/5020ea703cb9962776eaef8d8a92d32b85916e4b/wholeslidedata/samplers/labelsampler.py#L113), i.e., the labels and the seed,  can now be set to a dictionary and an integer, respectively.  The notation ${wholeslidedata:seed} ensures that we can get the 'seed' defined earlier in the config, in this case, the seed is 2 and this 2 is now also used as the seed in the label_sampler.  

I hope this clarifies the config a bit. Please let me know if you have any additional questions.

Best wishes,
Mart
